name: dashboard-indicadores
services:
  database:
    build:
      context: ./database
      dockerfile: Dockerfile
    user: "${UID:-1000}:${GID:-1000}"
    restart: always
    shm_size: 128mb
    environment:
      TZ: America/Sao_Paulo
      PGTZ: America/Sao_Paulo
      LANG: en_US
      LANGUAGE: en_US
      LC_ALL: pt_BR.UTF-8
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_INITDB_ARGS: "--lc-numeric=pt_BR.UTF-8 --lc-monetary=pt_BR.UTF-8 --lc-collate=pt_BR.UTF-8 --lc-ctype=pt_BR.UTF-8"
    ports:
      - "5432:5432"
    volumes:
      - ./database/sql/seeds/data:/tmp/seeds
      - ./database/schema.sql:/docker-entrypoint-initdb.d/01_schema.sql
      - ./database/sql/seeds/seed_indicadores.sql:/docker-entrypoint-initdb.d/02_seeds.sql
      - ./database/sql/seeds/seed_superintendencias.sql:/docker-entrypoint-initdb.d/03_seeds.sql
      - ./database/sql/seeds/seed_tipo_de_unidade.sql:/docker-entrypoint-initdb.d/04_seeds.sql
      - ./database/sql/seeds/seed_indicador_tipo_de_unidade.sql:/docker-entrypoint-initdb.d/05_seeds.sql
      - ./database/sql/seeds/seed_unidades.sql:/docker-entrypoint-initdb.d/06_seeds.sql
      - ./database/sql/seeds/seed_resultados.sql:/docker-entrypoint-initdb.d/07_seeds.sql
      - ./database/sql/views/vw_indicadores_sih.sql:/docker-entrypoint-initdb.d/08_view.sql
      - ./database/sql/views/vw_indicadores_sia_resumo.sql:/docker-entrypoint-initdb.d/09_view.sql
      - ./database/sql/views/vw_indicadores_sia_especialidades.sql:/docker-entrypoint-initdb.d/10_view.sql
      # - ./docker/database/data:/var/lib/postgresql/MAJOR/data
      - /etc/localtime:/etc/localtime:ro
    networks:
      - dashboard
  pgadmin:
    image: dpage/pgadmin4:latest
    ports:
      - 8080:80
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@postgres.com
      PGADMIN_DEFAULT_PASSWORD: postgres
    volumes:
      - ./docker/pgadmin/data:/var/lib/pgadmin/data
    mem_limit: "2gb"
    cpus: "1"
    networks:
      - dashboard
  n8n:
    image: docker.n8n.io/n8nio/n8n
    container_name: n8n_dashify
    # Executa o n8n com o seu usuário local
    user: "${UID:-1000}:${GID:-1000}"
    restart: unless-stopped
    ports:
      - "5678:5678"
    environment:
      - N8N_HOST=0.0.0.0
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - NODE_ENV=production
      - WEBHOOK_URL=http://localhost:5678/
      - GENERIC_TIMEZONE=America/Sao_Paulo
    volumes:
      - ./docker/n8n_data:/home/node/.n8n
    networks:
      - dashboard
networks:
  dashboard:
    driver: bridge
