name: dashboard-indicadores
services:
  database:
    build:
      context: ./database
      dockerfile: Dockerfile
    restart: always
    shm_size: 128mb
    environment:
      TZ: America/Sao_Paulo
      PGTZ: America/Sao_Paulo
      LANG: en_US
      LANGUAGE: en_US
      LC_ALL: pt_BR.UTF-8
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_INITDB_ARGS: "--lc-numeric=pt_BR.UTF-8 --lc-monetary=pt_BR.UTF-8 --lc-collate=pt_BR.UTF-8 --lc-ctype=pt_BR.UTF-8"
    ports:
      - "5432:5432"
    volumes:
      - ./database/seeds:/tmp/seeds
      - ./docker/database/data:/var/lib/postgresql/MAJOR/data
      - ./database/schema.sql:/docker-entrypoint-initdb.d/01_schema.sql
      - ./database/seed_indicadores.sql:/docker-entrypoint-initdb.d/02_seeds.sql
      - ./database/seed_tipo_de_unidade.sql:/docker-entrypoint-initdb.d/03_seeds.sql
      - ./database/seed_unidades.sql:/docker-entrypoint-initdb.d/04_seeds.sql
      - ./database/seed_resultados.sql:/docker-entrypoint-initdb.d/05_seeds.sql
      - /etc/localtime:/etc/localtime:ro
    networks:
      - dashboard
  pgadmin:
    image: dpage/pgadmin4:latest
    ports:
      - 8080:80
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@postgres.com
      PGADMIN_DEFAULT_PASSWORD: postgres
    volumes:
      - ./docker/pgadmin/data:/var/lib/pgadmin/data
    mem_limit: "2gb"
    cpus: "1"
    networks:
      - dashboard
networks:
  dashboard:
    driver: bridge
