name: Release Pipeline

# O workflow só será disparado quando houver um push (merge de PR) nessas branches
on:
    push:
        branches:
            - main
            - stage
            - dev
            - 1.x

# Permissões cruciais para o @semantic-release/git conseguir fazer o commit de volta
permissions:
    contents: write # Permite criar tags e commitar o CHANGELOG/package.json
    issues: write # Permite comentar em issues (se usar o plugin do github)
    pull-requests: write # Permite comentar em PRs

jobs:
    release:
        name: Build, Test & Release
        runs-on: ubuntu-latest

        steps:
            - name: Checkout do repositório
              uses: actions/checkout@v4
              with:
                  # O Semantic Release precisa de todo o histórico (todas as tags e commits)
                  # para calcular a próxima versão corretamente. O padrão é 1, precisa ser 0.
                  fetch-depth: 0

                  # Garante que o checkout usa um token com permissão para burlar proteção de branch se necessário
                  # token: ${{ secrets.GH_TOKEN }} # Pode precisar de um PAT dependendo das regras do repositório

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: "20" # Ajuste para a versão que você usa no projeto
                  cache: "npm"

            - name: Instalar Dependências
              run: npm ci

            - name: Executar Semantic Release
              run: >
                  npx 
                  --package semantic-release 
                  --package @semantic-release/changelog 
                  --package @semantic-release/git 
                  --package conventional-changelog-conventionalcommits 
                  semantic-release
